### ISSUE TITLE
As a Builder, I want a Test App, so I can quickly try out the protocol without coding anything.

### ISSUE THREAD

**Issue by MantisClone** [RequestNetwork/request-apps#67]
# Definition of Done

- [ ] Fix Request Create to use ETH_FEE_PROXY instead of ETH_INPUT_DATA
- [ ] Fix Request Create to NOT require switching to Gnosis when creating a request
- [ ] Fix the Create page to update when a request is confirmed without requiring a refresh #62 
- [ ] Fix the Dashboard; fails to fetch balance for MATIC requests #60 
- [ ] Fix build to support Node 18 #57 
- [ ] Fix error when changing to xDAI chain but xDAI wasn't previously added to Metamask #51 
- [ ] https://github.com/RequestNetwork/request-apps/issues/72

---

Migrated from Asana: https://app.asana.com/0/1203912381456855/1205287813635970/f

**Comment by MantisClone** [comment]
We decided to deprecate and shut down [Request Create](https://create.request.network)
